### ISSUE TITLE
Percent correct always shows 100%

### ISSUE THREAD

**Issue by xflashkey** [ankipalace/advanced-browser#128] opened 2021-08-07 23:52 UTC
Am i missing something? If i see the percent correct filter every card has 100% in all the cardseven the forgotten ones
. Is this a bug?  
![image](https://user-images.githubusercontent.com/72907488/128616494-8634cc93-b365-4c38-85bb-557e927a3dfe.png)

**Comment by Arthur-Milchior** [comment] 2021-08-08 03:14
I can't reproduce right now. Seems strange.
Could you please also show the content of the columns Lapses and Reviews? If lapses is 0, as I expect, it may explain things

It would be helpful, during bug report, to have things such as anki version, whether you did try to update the add-ons and restarted.
My best intuition would be that you are using the scheduler V3. But it seems I can't just switch to it, so I I'm confused

**Comment by ijgnd** [comment] 2022-01-30 13:59
Due to a lack of additional information I'm closing this. If you still have this problem and want to provide additional info re-open the issue.

**Closed by ijgnd** 2022-01-30 13:59 UTC
