### ISSUE TITLE
Advanced Browser crashes Anki if card is flagged as Turquoise

### ISSUE THREAD

**Issue by SommerofWeimar** [ankipalace/advanced-browser#140] opened 2022-03-16 14:39 UTC
Advanced browser will crash Anki if you open the "browse" tab and have cards flagged as turquoise. I presume that this is because the turquoise flag exists on the official Anki iOS app but possibly not the current desktop version. I haven't tested this with all iOS flag colors but I imagine that the issue will also occur with other flags that aren't(?) on the desktop version. This issue does NOT occur with cards that are flagged as red, blue, green or orange - I presume because these are available on both the desktop and iOS anki versions. I have attached my error report below:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.43 (0fbae6bc) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-03-16 09:16:59

Caught exception:
Traceback (most recent call last):
  File "C:\Users\MYNAMEHERE\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 176, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt\browser.py", line 415, in paint
AttributeError: module 'aqt.colors' has no attribute 'FLAG6_BG'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\MYNAMEHERE\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 176, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt\browser.py", line 415, in paint
AttributeError: module 'aqt.colors' has no attribute 'FLAG6_BG'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\MYNAMEHERE\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 176, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt\browser.py", line 415, in paint
AttributeError: module 'aqt.colors' has no attribute 'FLAG6_BG'

Caught exception:
Traceback (most recent call last):
  File "C:\Users\MYNAMEHERE\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 176, in paint
    return super(AdvancedStatusDelegate, self).paint(painter, option, index)
  File "aqt\browser.py", line 415, in paint
AttributeError: module 'aqt.colors' has no attribute 'FLAG6_BG'

**Comment by ijgnd** [comment] 2022-04-01 13:34
You have Anki 2.1.43. This has not been the current version since 2021-05-04, see https://changes.ankiweb.net/changes/2.1.40-49.html.

As far as I see it was Anki 2.1.45 that introduced support for new flags, see https://changes.ankiweb.net/changes/2.1.40-49.html#changes-in-2145

So you should run into the same problem without all add-ons disabled? Do the steps from the official troubleshooting guide, Have https://faqs.ankiweb.net/when-problems-occur.html Do you still have this problem if you start anki while pressing shift? If so the problem is not about this add-on.

This has been discussed many times in the official forum, see e.g. https://forums.ankiweb.net/t/attributeerror-module-aqt-colors-has-no-attribute-flag6-bg/13370

I'm pretty sure that you have the same problem. So I close this issue. But if the problem occurs in 2.1.49 with the advaced browser reopen it.

**Closed by ijgnd** 2022-04-01 13:34 UTC
