### ISSUE TITLE
"OR" does not work in searchfield

### ISSUE THREAD

**Issue by honis56** [ankipalace/advanced-browser#127] opened 2021-08-01 11:11 UTC
Hi,

in ""search card notes" the "OR"- operator behaves as an "AND"-Operator. 

Example:
california OR Kalifornien 

results in nothing, although each keyword has results when standing alone.

Best regards

**Comment by Arthur-Milchior** [comment] 2021-08-02 01:26
Hi,

Thanks for this report
Did you try with this add-on turned off?

Normally, this add-on do not deal with the search feature at all. It adds column to the result of the search. 
So I'd strongly suspect another add-on is causing this.

I could theoretically imagine the interaction between two add-ons, but honestly, I can't even figure out which part of the advanced browser would cause it.


Another thing you can try would be to use "california OR Kalifornien" in a filtered deck and see whether you get anything. Filtered deck and browser use the same search setting, so if it's a problem with search, you'll see it. (Assuming that you use the correct setting. That is, finding cards that are new/reviewed/suspended, so that your card speaking of California are not filtered out for another reason)

**Comment by honis56** [comment] 2021-08-03 11:49
> 
> 
> Hi,
> 
> Thanks for this report
> Did you try with this add-on turned off?
> 
Same problem when add-on "advanced browser" is turned off.

Best regards

**Comment by honis56** [comment] 2021-11-14 10:17
Very strange: 
Now "or" is okay in pure Anki but does not work with addon advanced browser.
I have proofed this error by using tags.

Version ⁨2.1.47 (dc156f34)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

Best regards

**Comment by ijgnd** [comment] 2022-01-30 13:05
I can't reproduce this problem either.

@honis56: Do you still have this problem? If so: could you disable all other add-ons, update to Anki 2.1.49, use the latest advanced browser version and try again to see if you still have this problem, see https://faqs.ankiweb.net/when-problems-occur.html

**Comment by ijgnd** [comment] 2022-01-30 13:56
If you still have this problem please re-open this issue. I'm closing this to get a better overview of the current issues of the advanced browser.

**Closed by ijgnd** 2022-01-30 13:56 UTC

**Comment by honis56** [comment] 2022-01-30 20:08
Sorry, I still have the problem even though I updated.
As I found out, it occurs together with the addon "Ignore accents in browser search".

https://ankiweb.net/shared/info/1924690148

Best regards
